name: Compiling-TeX
on:
  push:
    branches:
      - master
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:

    - name: Set up Git repository
      uses: actions/checkout@v1

    - name: Compile Abstract
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: abstract

    - name: Check pdf files
      run: |
        file abstract/main.pdf | grep -q ' PDF '

    - name: Upload
      run: |
        # configure git
        git config --global user.name "mxochicale"
        git config --global user.email "perez.xochicale@gmail.com"
        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git clone --depth=1 --branch pdf git@github.com:mxochicale/rrts2020.git "$GITHUB_WORKSPACE/deploy"
        cp -f abstract/main.pdf "$GITHUB_WORKSPACE/deploy/abstract.pdf"
        cd "$GITHUB_WORKSPACE/deploy"
        git add abstract.pdf
        git commit -m "[github actions] deploy"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
